name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Install Pipenv
        run: |
          python -m pip install pipenv
          
      - name: Install Python and Pipenv
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
          pipenv: true
          
      - name: Install dependencies
        run: |
          pipenv --python 3.9 install --deploy --ignore-pipfile

      - name: Run tests
        run: pipenv run python manage.py test
